const challengeTemplates = [
  {
    id: "catch-ten-min",
    title: "Catch a fish in 10min",
    type: "timed",
    scheduleType: "daily",
    timeLimit: 600,
    fishKey: null,
    goal: 1,
    rewardXp: 1000,
    difficulty: "hard",
    verificationMode: "auto",
  },
  {
    id: "catch-thirty-min",
    title: "Catch a fish in 30min",
    type: "timed",
    scheduleType: "daily",
    timeLimit: 1800,
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },
  {
    id: "snag-lure",
    title: "Snag your lure or catch debris",
    type: "species_count",
    scheduleType: "daily",
    fishKey: "debri",
    goal: 1,
    rewardXp: 300,
    difficulty: "very easy",
    verificationMode: "manual",
  },
  {
    id: "first-cast",
    title: "Catch a fish on your first cast",
    type: "luck",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 1500,
    difficulty: "very hard",
    verificationMode: "manual",
  },
  {
    id: "catch-two-min",
    title: "Catch a fish within 2 minutes",
    type: "timed",
    scheduleType: "daily",
    timeLimit: 120,
    fishKey: null,
    goal: 1,
    rewardXp: 1500,
    difficulty: "very hard",
    verificationMode: "auto",
  },
  {
    id: "lose-fish",
    title: "Lose a fish while reeling it in",
    type: "luck",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
    difficulty: "very easy",
    verificationMode: "manual",
  },
  {
    id: "new-location",
    title: "Fish at a new location",
    type: "adventure",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
    difficulty: "very easy",
    verificationMode: "auto",
  },
  {
    id: "early-catch",
    title: "Catch a fish before sunrise",
    type: "adventure",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },
  {
    id: "night-catch",
    title: "Catch a fish after sunset",
    type: "adventure",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },
  {
    id: "rain-fisher",
    title: "Catch a fish while it's raining",
    type: "adventure",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },

  {
    id: "three-diff-species",
    title: "Catch 3 different species",
    type: "species_count",
    scheduleType: "daily",
    fishKey: null,
    goal: 3,
    rewardXp: 1500,
    difficulty: "very hard",
    verificationMode: "auto",
  },

  {
    id: "use-live-bait",
    title: "Catch a fish using live bait",
    type: "rig",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },
  {
    id: "use-worms",
    title: "Catch a fish using a worm",
    type: "rig",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },
  {
    id: "use-crankbait",
    title: "Catch a fish using a crankbait",
    type: "rig",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },
  {
    id: "use-spinnerbait",
    title: "Catch a fish using a spinnerbait",
    type: "rig",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },
  {
    id: "use-bobber",
    title: "Catch a fish using a bobber",
    type: "rig",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },
  {
    id: "use-texas-rig",
    title: "Catch a fish using a Texas rig",
    type: "rig",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },
  {
    id: "use-dropshot",
    title: "Catch a fish using a dropshot rig",
    type: "rig",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },
  {
    id: "use-topwater",
    title: "Catch a fish using a topwater bait",
    type: "rig",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 500,
    difficulty: "easy",
    verificationMode: "auto",
  },

  {
    id: "empty-hook",
    title: "Reel in with no bait left",
    type: "luck",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
    difficulty: "very easy",
    verificationMode: "manual",
  },
  {
    id: "small-fish",
    title: "Catch a small fish",
    type: "species_size",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
    difficulty: "very easy",
    verificationMode: "auto",
  },
  {
    id: "trophy-fish",
    title: "Catch a trohpy fish",
    type: "species_size",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 1500,
    difficulty: "very hard",
    verificationMode: "auto",
  },
  {
    id: "medium-fish",
    title: "Catch a medium fish",
    type: "species_size",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 1000,
    difficulty: "hard",
    verificationMode: "auto",
  },
];

export default challengeTemplates;
