const challengeTemplates = [
  {
    id: "catch-ten-min",
    title: "Catch a fish in 10min",
    type: "timed",
    scheduleType: "daily",
    timeLimit: 600,
    fishKey: null,
    goal: 1,
    rewardXp: 1000,
  },
  {
    id: "snag-lure",
    title: "Snag your lure or catch debris",
    type: "species_count",
    scheduleType: "static",
    fishKey: "debri",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "first-cast",
    title: "Catch a fish on your first cast",
    type: "luck",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 1500,
  },
  {
    id: "catch-two-min",
    title: "Catch a fish within 2 minutes",
    type: "timed",
    scheduleType: "daily",
    timeLimit: 120,
    fishKey: null,
    goal: 1,
    rewardXp: 1000,
  },
  {
    id: "lose-fish",
    title: "Lose a fish while reeling it in",
    type: "luck",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "new-location",
    title: "Fish at a new location",
    type: "adventure",
    scheduleType: "static",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "early-catch",
    title: "Catch a fish before sunrise",
    type: "adventure",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "night-catch",
    title: "Catch a fish after sunset",
    type: "adventure",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "rain-fisher",
    title: "Catch a fish while it's raining",
    type: "adventure",
    scheduleType: "daily",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },

  {
    id: "three-diff-species",
    title: "Catch 3 different species",
    type: "species_count",
    scheduleType: "static",
    fishKey: null,
    goal: 3,
    rewardXp: 300,
  },
  {
    id: "five-diff-species",
    title: "Catch 5 different species",
    type: "species_count",
    scheduleType: "static",
    fishKey: null,
    goal: 5,
    rewardXp: 500,
  },

  {
    id: "use-live-bait",
    title: "Catch a fish using live bait",
    type: "rig",
    scheduleType: "static",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "use-worms",
    title: "Catch a fish using a worm",
    type: "rig",
    scheduleType: "static",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "use-crankbait",
    title: "Catch a fish using a crankbait",
    type: "rig",
    scheduleType: "static",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "use-spinnerbait",
    title: "Catch a fish using a spinnerbait",
    type: "rig",
    scheduleType: "static",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "use-bobber",
    title: "Catch a fish using a bobber",
    type: "rig",
    scheduleType: "static",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "use-texas-rig",
    title: "Catch a fish using a Texas rig",
    type: "rig",
    scheduleType: "static",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "use-dropshot",
    title: "Catch a fish using a dropshot rig",
    type: "rig",
    scheduleType: "static",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "use-topwater",
    title: "Catch a fish using a topwater bait",
    type: "rig",
    scheduleType: "static",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },

  {
    id: "empty-hook",
    title: "Reel in with no bait left",
    type: "luck",
    scheduleType: "static",
    fishKey: null,
    goal: 1,
    rewardXp: 300,
  },

  {
    id: "catch-a-panfish",
    title: "Catch a Panfish",
    type: "species_count",
    scheduleType: "static",
    fishKey: "panfish",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "catch-3-panfish",
    title: "Catch 3 Panfish",
    type: "species_count",
    scheduleType: "static",
    fishKey: "panfish",
    goal: 3,
    rewardXp: 500,
  },

  {
    id: "catch-a-carp",
    title: "Catch a Carp",
    type: "species_count",
    scheduleType: "static",
    fishKey: "carp",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "catch-3-carp",
    title: "Catch 3 Carp",
    type: "species_count",
    scheduleType: "static",
    fishKey: "carp",
    goal: 3,
    rewardXp: 500,
  },

  {
    id: "catch-a-bass",
    title: "Catch a Bass",
    type: "species_count",
    scheduleType: "static",
    fishKey: "bass",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "catch-3-bass",
    title: "Catch 3 Bass",
    type: "species_count",
    scheduleType: "static",
    fishKey: "bass",
    goal: 3,
    rewardXp: 500,
  },

  {
    id: "catch-a-bluegill",
    title: "Catch a Bluegill",
    type: "species_count",
    scheduleType: "static",
    fishKey: "bluegill",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "catch-3-bluegill",
    title: "Catch 3 Bluegill",
    type: "species_count",
    scheduleType: "static",
    fishKey: "bluegill",
    goal: 3,
    rewardXp: 500,
  },

  {
    id: "catch-a-catfish",
    title: "Catch a Catfish",
    type: "species_count",
    scheduleType: "static",
    fishKey: "catfish",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "catch-3-catfish",
    title: "Catch 3 Catfish",
    type: "species_count",
    scheduleType: "static",
    fishKey: "catfish",
    goal: 3,
    rewardXp: 500,
  },

  {
    id: "catch-a-crappie",
    title: "Catch a Crappie",
    type: "species_count",
    scheduleType: "static",
    fishKey: "crappie",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "catch-3-crappie",
    title: "Catch 3 Crappie",
    type: "species_count",
    scheduleType: "static",
    fishKey: "crappie",
    goal: 3,
    rewardXp: 500,
  },

  {
    id: "catch-a-pike",
    title: "Catch a Pike",
    type: "species_count",
    scheduleType: "static",
    fishKey: "pike",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "catch-3-pike",
    title: "Catch 3 Pike",
    type: "species_count",
    scheduleType: "static",
    fishKey: "pike",
    goal: 3,
    rewardXp: 500,
  },

  {
    id: "catch-a-sunfish",
    title: "Catch a Sunfish",
    type: "species_count",
    scheduleType: "static",
    fishKey: "sunfish",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "catch-3-sunfish",
    title: "Catch 3 Sunfish",
    type: "species_count",
    scheduleType: "static",
    fishKey: "sunfish",
    goal: 3,
    rewardXp: 500,
  },

  {
    id: "catch-a-trout",
    title: "Catch a Trout",
    type: "species_count",
    scheduleType: "static",
    fishKey: "trout",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "catch-3-trout",
    title: "Catch 3 Trout",
    type: "species_count",
    scheduleType: "static",
    fishKey: "trout",
    goal: 3,
    rewardXp: 500,
  },

  {
    id: "catch-a-walleye",
    title: "Catch a Walleye",
    type: "species_count",
    scheduleType: "static",
    fishKey: "walleye",
    goal: 1,
    rewardXp: 300,
  },
  {
    id: "catch-3-walleye",
    title: "Catch 3 Walleye",
    type: "species_count",
    scheduleType: "static",
    fishKey: "walleye",
    goal: 3,
    rewardXp: 500,
  },
];

export default challengeTemplates;
